[package]
name = "rusty_keyboard"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = "0.2.133"
log = "0.4.17"
winapi = { version = "0.3.9", features = ["winuser"] }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

